import Header from '@/components/Header';
import '../style/globals.css';
import PromptInput from '@/components/PromptInput';
import ClientProvider from "@/components/ClientProvider";

export const metadata = {
  title: 'DALL·E 2 || Image Generator',
  description: 'Generated by Dev Huzaifa',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <Header/>
          <PromptInput/>
        </ClientProvider>
        {children}
      </body>
    </html>
  )
}
